### TPC Benchmarking  
Results Plotting

In [1]:
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

sns.set_context("notebook", font_scale=1.0, rc={"lines.linewidth": 1.0})

import config, sfa, bqa, tools

In [2]:
from importlib import reload

In [3]:
reload(sfa)
sf = sfa.SFTPC(test="ds",
               scale=1,
               cid="01",
               warehouse="TEST9000",
               desc="query_history",
               verbose=False,
               verbose_query=False)
sf.connect()
df_result, qid = sf.query_history(t0=pd.Timestamp.now() - pd.Timedelta("72 hours"),
                                 t1=pd.Timestamp.now())
sf.close()

In [16]:
df_result.head()

,creation_time,project_id,project_number,user_email,job_id,job_type,statement_type,start_time,end_time,query,...,reservation_id,total_bytes_processed,total_slot_ms,error_result,cache_hit,destination_table,referenced_tables,labels,timeline,job_stages
0,2020-05-15 18:09:55.415000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,258206cb-0959-4b9f-9918-e299cf5c0f67,QUERY,SCRIPT,2020-05-15 18:09:55.453000+00:00,2020-05-15 18:10:03.723000+00:00,\nwith cross_items as\n (select i_item_sk ss_...,...,None,321943280,138521,None,None,"{'project_id': 'tpc-benchmarking-9432', 'datas...",[],"[{'key': 'label', 'value': 'ds_1gb_01-q14-t2-d...",[],[]
1,2020-05-15 18:13:29.977000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,f8f99246-7811-4aa8-8195-71ed29b0afc5,QUERY,SCRIPT,2020-05-15 18:13:30.012000+00:00,2020-05-15 18:13:43.870000+00:00,\nwith frequent_ss_items as \n (select substr(...,...,None,406389632,114320,None,None,"{'project_id': 'tpc-benchmarking-9432', 'datas...",[],"[{'key': 'label', 'value': 'ds_1gb_01-q23-t2-d...",[],[]
2,2020-05-15 18:10:42.274000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,34b4ed95-c0a1-4b43-aadb-1eb111d38986,QUERY,SCRIPT,2020-05-15 18:10:42.342000+00:00,2020-05-15 18:10:49.931000+00:00,"\nwith ssales as\n(select c_last_name\n ,...",...,None,246842570,16361,None,None,"{'project_id': 'tpc-benchmarking-9432', 'datas...",[],"[{'key': 'label', 'value': 'ds_1gb_01-q24-t2-d...",[],[]
3,2020-05-15 18:09:55.718000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,script_job_0fb845434cecbff6f44b892f95bf3349_0,QUERY,SELECT,2020-05-15 18:09:55.891000+00:00,2020-05-15 18:09:59.360000+00:00,with cross_items as\n (select i_item_sk ss_it...,...,None,160387248,72177,None,False,"{'project_id': 'tpc-benchmarking-9432', 'datas...","[{'project_id': 'tpc-benchmarking-9432', 'data...","[{'key': 'label', 'value': 'ds_1gb_01-q14-t2-d...","[{'elapsed_ms': 707, 'total_slot_ms': 2489, 'p...","[{'name': 'S00: Input', 'id': 0, 'start_ms': 1..."
4,2020-05-15 18:10:28.605000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,5cf1d52d-db4f-4fe8-9c9a-951ea819aa30,QUERY,SELECT,2020-05-15 18:10:28.783000+00:00,2020-05-15 18:10:30.276000+00:00,\nselect *\nfrom\n (select count(*) h8_30_to_...,...,None,68293214,8348,None,False,"{'project_id': 'tpc-benchmarking-9432', 'datas...","[{'project_id': 'tpc-benchmarking-9432', 'data...","[{'key': 'label', 'value': 'ds_1gb_01-q88-t2-d...","[{'elapsed_ms': 635, 'total_slot_ms': 1645, 'p...","[{'name': 'S00: Input', 'id': 0, 'start_ms': 1..."

In [4]:
qid

'019450bd-0237-01f0-0009-c08300033a6e'

In [13]:
reload(bqa)
bq = bqa.BQTPC(test="ds",
               scale=1,
               cid="01",
               desc="query_history",
               verbose=True,
               verbose_query=True)
#bq.timestamp = timestamp
#bq.results_dir = test_name

df_result, qid = bq.query_history(t0=pd.Timestamp.now() - pd.Timedelta("72 hours"),
                                  t1=pd.Timestamp.now())

BigQuery configuration
=======================
Service Account:  bq-476262002685@bigquery-encryption.iam.gserviceaccount.com

QUERY TEXT
==========
select * from `region-us`.INFORMATION_SCHEMA.JOBS_BY_PROJECT where job_type = 'QUERY' and end_time between '2020-05-15 13:20:56' AND '2020-05-18 13:20:56'

In [15]:
qid

'b7e60a41-9877-42f3-aaa4-20d49524fef8'

In [14]:
df_result.head()

,creation_time,project_id,project_number,user_email,job_id,job_type,statement_type,start_time,end_time,query,...,reservation_id,total_bytes_processed,total_slot_ms,error_result,cache_hit,destination_table,referenced_tables,labels,timeline,job_stages
0,2020-05-15 18:09:55.415000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,258206cb-0959-4b9f-9918-e299cf5c0f67,QUERY,SCRIPT,2020-05-15 18:09:55.453000+00:00,2020-05-15 18:10:03.723000+00:00,\nwith cross_items as\n (select i_item_sk ss_...,...,None,321943280,138521,None,None,"{'project_id': 'tpc-benchmarking-9432', 'datas...",[],"[{'key': 'label', 'value': 'ds_1gb_01-q14-t2-d...",[],[]
1,2020-05-15 18:13:29.977000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,f8f99246-7811-4aa8-8195-71ed29b0afc5,QUERY,SCRIPT,2020-05-15 18:13:30.012000+00:00,2020-05-15 18:13:43.870000+00:00,\nwith frequent_ss_items as \n (select substr(...,...,None,406389632,114320,None,None,"{'project_id': 'tpc-benchmarking-9432', 'datas...",[],"[{'key': 'label', 'value': 'ds_1gb_01-q23-t2-d...",[],[]
2,2020-05-15 18:10:42.274000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,34b4ed95-c0a1-4b43-aadb-1eb111d38986,QUERY,SCRIPT,2020-05-15 18:10:42.342000+00:00,2020-05-15 18:10:49.931000+00:00,"\nwith ssales as\n(select c_last_name\n ,...",...,None,246842570,16361,None,None,"{'project_id': 'tpc-benchmarking-9432', 'datas...",[],"[{'key': 'label', 'value': 'ds_1gb_01-q24-t2-d...",[],[]
3,2020-05-15 18:09:55.718000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,script_job_0fb845434cecbff6f44b892f95bf3349_0,QUERY,SELECT,2020-05-15 18:09:55.891000+00:00,2020-05-15 18:09:59.360000+00:00,with cross_items as\n (select i_item_sk ss_it...,...,None,160387248,72177,None,False,"{'project_id': 'tpc-benchmarking-9432', 'datas...","[{'project_id': 'tpc-benchmarking-9432', 'data...","[{'key': 'label', 'value': 'ds_1gb_01-q14-t2-d...","[{'elapsed_ms': 707, 'total_slot_ms': 2489, 'p...","[{'name': 'S00: Input', 'id': 0, 'start_ms': 1..."
4,2020-05-15 18:10:28.605000+00:00,tpc-benchmarking-9432,476262002685,476262002685-compute@developer.gserviceaccount...,5cf1d52d-db4f-4fe8-9c9a-951ea819aa30,QUERY,SELECT,2020-05-15 18:10:28.783000+00:00,2020-05-15 18:10:30.276000+00:00,\nselect *\nfrom\n (select count(*) h8_30_to_...,...,None,68293214,8348,None,False,"{'project_id': 'tpc-benchmarking-9432', 'datas...","[{'project_id': 'tpc-benchmarking-9432', 'data...","[{'key': 'label', 'value': 'ds_1gb_01-q88-t2-d...","[{'elapsed_ms': 635, 'total_slot_ms': 1645, 'p...","[{'name': 'S00: Input', 'id': 0, 'start_ms': 1..."