In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import qc, config, tools

from importlib import reload

pd.options.display.max_rows = 9999
pd.options.display.max_columns = 9999

1. setup local
2. data upload from VM to GCS
3. data upload from GCS to BQ/SF
4.

## Instructions to Use  
Further information

In [2]:
reload(qc)

data_qc = qc.QueryQC()
data_qc.test = "h"  # change to test to run "h" or "ds"
data_qc.scale = 1
data_qc.cid = "01"
data_qc.stream_n = 1
data_qc.desc =  f"load_check"
data_qc.seq_id = "NA"

data_qc.verbose = False
data_qc.verbose_query = False
data_qc.qual = False
data_qc.save = True
data_qc.verbose_iter = True

data_qc.set_timestamp_dir()

df_result = data_qc.compare_sum()

Result Folder Name:
/home/colin/code/bq_snowflake_benchmark/results/bqsf_h_01_results--load_check-2020-06-10_12:42:09.675118
TABLE & COLUMN: customer >> c_custkey
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
11250075000 | 11250075000
----------------------------------------

TABLE & COLUMN: lineitem >> l_linenumber
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
18007100 | 18007100
----------------------------------------

TABLE & COLUMN: nation >> n_nationkey
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
300 | 300
----------------------------------------

TABLE & COLUMN: orders >> o_orderkey
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
4499987250000 | 4499987250000
----------------------------------------

TABLE & COLUMN: part >> p_partkey
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
20000100000 | 20000100000
----------------------------------------

TABLE & COLUMN: partsupp >> ps_partkey
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
80000400000 | 80000400000
----------------------------------------

TABLE & COLUMN: region >> r_regionkey
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
10 | 10
----------------------------------------

TABLE & COLUMN: supplier >> s_suppkey
RESULT: SF | BQ
SF Type: <class 'numpy.int64'>
BQ Type: <class 'numpy.int64'>
50005000 | 50005000
----------------------------------------

In [3]:
df_result

      table        column             sf             bq  equal
0  customer     c_custkey    11250075000    11250075000   True
1  lineitem  l_linenumber       18007100       18007100   True
2    nation   n_nationkey            300            300   True
3    orders    o_orderkey  4499987250000  4499987250000   True
4      part     p_partkey    20000100000    20000100000   True
5  partsupp    ps_partkey    80000400000    80000400000   True
6    region   r_regionkey             10             10   True
7  supplier     s_suppkey       50005000       50005000   True